import os
import requests
import streamlit as st


ANOMALY_DETECTOR_URL = os.getenv(
    "ANOMALY_DETECTOR_URL",
    "http://localhost:8004",
)

TRAFFIC_GENERATOR_URL = os.getenv(
    "TRAFFIC_GENERATOR_URL",
    "http://localhost:8005",
)

SERVICE_URLS = {
    "order-service": os.getenv("ORDER_SERVICE_URL", "http://localhost:8001"),
    "user-service": os.getenv("USER_SERVICE_URL", "http://localhost:8002"),
    "inventory-service": os.getenv("INVENTORY_SERVICE_URL", "http://localhost:8003"),
}


st.set_page_config(
    page_title="AI Incident Copilot",
    page_icon="",
    layout="wide",
)


def get_json(url: str):
    response = requests.get(url, timeout=5)
    response.raise_for_status()
    return response.json()

def post_json(url: str):
    response = requests.post(url, timeout=30)
    response.raise_for_status()
    return response.json()


def trigger_error(service_name: str):
    url = f"{SERVICE_URLS[service_name]}/simulate/error"
    try:
        requests.get(url, timeout=5)
    except requests.RequestException:
        pass


def trigger_slow(service_name: str, delay_seconds: float):
    url = f"{SERVICE_URLS[service_name]}/simulate/slow"
    try:
        requests.get(url, params={"delay_seconds": delay_seconds}, timeout=delay_seconds + 5)
    except requests.RequestException:
        pass


st.title(" AI Incident Copilot")
st.caption("Observability dashboard for detecting incidents, summarizing root-cause hypotheses, and recommending actions.")

col1, col2, col3 = st.columns(3)

with col1:
    if st.button("Refresh Incident Report"):
        st.rerun()

with col2:
    st.link_button("Open Prometheus", "http://localhost:9090")

with col3:
    st.link_button("Open Grafana", "http://localhost:3000")


st.divider()

try:
    llm_response = get_json(f"{ANOMALY_DETECTOR_URL}/report/llm")
    report = llm_response.get("base_report", {})
except requests.RequestException as exc:
    st.error(f"Could not reach anomaly-detector: {exc}")
    st.stop()


status = report.get("status", "unknown")
incident_count = report.get("incident_count", 0)

metric_col1, metric_col2, metric_col3 = st.columns(3)

with metric_col1:
    st.metric("System Status", status)

with metric_col2:
    st.metric("Active Incidents", incident_count)

with metric_col3:
    st.metric("Checked At", report.get("checked_at", "unknown"))


if status == "normal":
    st.success("No active incidents detected.")
else:
    st.error("Incident detected.")


st.subheader("Summary")
st.write(report.get("summary", "No summary available."))

st.subheader("Root Cause Hypothesis")
st.write(report.get("root_cause_hypothesis", "No hypothesis available."))
st.subheader("LLM Incident Analysis")

if st.button("Save Current Incident Snapshot"):
    try:
        saved_report = post_json(f"{ANOMALY_DETECTOR_URL}/report/llm/save")
        st.success(f"Saved incident snapshot: {saved_report.get('report_id')}")
    except requests.RequestException as exc:
        st.error(f"Could not save incident snapshot: {exc}")

if llm_response.get("llm_enabled"):
    st.info(f"Generated by model: {llm_response.get('llm_model')}")
else:
    st.warning("LLM is disabled. Add OPENAI_API_KEY to enable AI-generated analysis.")

st.write(llm_response.get("llm_analysis", "No LLM analysis available."))

st.subheader("Recommended Actions")
for action in report.get("recommended_actions", []):
    st.write(f"- {action}")


st.subheader("Active Incidents")
incidents = report.get("incidents", [])

if not incidents:
    st.info("No active incidents.")
else:
    for incident in incidents:
        with st.container(border=True):
            st.write(f"**Service:** {incident.get('service')}")
            st.write(f"**Type:** {incident.get('type')}")
            st.write(f"**Severity:** {incident.get('severity')}")
            st.write(f"**Value:** {incident.get('value')}")
            st.write(f"**Threshold:** {incident.get('threshold')}")
            st.write(f"**Message:** {incident.get('message')}")


st.divider()

st.subheader("Failure Injection Lab")

st.divider()

st.subheader("Demo Traffic Generator")
st.caption("Generate traffic automatically for Prometheus, Grafana, and incident detection demos.")

demo_col1, demo_col2, demo_col3, demo_col4 = st.columns(4)

with demo_col1:
    if st.button("Generate Normal Traffic"):
        try:
            result = post_json(f"{TRAFFIC_GENERATOR_URL}/generate/normal")
            st.success(f"Generated {result.get('total_requests')} normal requests.")
        except requests.RequestException as exc:
            st.error(f"Could not generate normal traffic: {exc}")

with demo_col2:
    if st.button("Generate Error Incident"):
        try:
            result = post_json(f"{TRAFFIC_GENERATOR_URL}/generate/errors?service_name=order-service&count=5")
            st.warning(f"Generated {result.get('total_requests')} error requests.")
        except requests.RequestException as exc:
            st.error(f"Could not generate error traffic: {exc}")

with demo_col3:
    if st.button("Generate Slow Incident"):
        try:
            result = post_json(f"{TRAFFIC_GENERATOR_URL}/generate/slow?service_name=user-service&count=3&delay_seconds=3")
            st.warning(f"Generated {result.get('total_requests')} slow requests.")
        except requests.RequestException as exc:
            st.error(f"Could not generate slow traffic: {exc}")

with demo_col4:
    if st.button("Generate Mixed Incident"):
        try:
            result = post_json(f"{TRAFFIC_GENERATOR_URL}/generate/mixed")
            st.error(f"Generated {result.get('total_requests')} mixed demo requests.")
        except requests.RequestException as exc:
            st.error(f"Could not generate mixed traffic: {exc}")
st.caption("Use these buttons to intentionally create errors or latency, then refresh the report after 5–10 seconds.")

service_name = st.selectbox(
    "Choose a service",
    ["order-service", "user-service", "inventory-service"],
)

delay_seconds = st.slider(
    "Slow request delay seconds",
    min_value=1.0,
    max_value=10.0,
    value=3.0,
    step=1.0,
)

inject_col1, inject_col2 = st.columns(2)

with inject_col1:
    if st.button("Trigger 500 Error"):
        trigger_error(service_name)
        st.warning(f"Triggered simulated error on {service_name}. Wait 5–10 seconds, then refresh.")

with inject_col2:
    if st.button("Trigger Slow Request"):
        trigger_slow(service_name, delay_seconds)
        st.warning(f"Triggered slow request on {service_name}. Wait 5–10 seconds, then refresh.")


st.divider()

st.subheader("Incident History")

try:
    history = get_json(f"{ANOMALY_DETECTOR_URL}/history?limit=10")
    reports = history.get("reports", [])

    if not reports:
        st.info("No saved incident snapshots yet.")
    else:
        for item in reports:
            with st.container(border=True):
                st.write(f"**Report ID:** {item.get('report_id')}")
                st.write(f"**Status:** {item.get('status')}")
                st.write(f"**Severity:** {item.get('severity')}")
                st.write(f"**Incident Count:** {item.get('incident_count')}")
                st.write(f"**Summary:** {item.get('summary')}")
                st.write(f"**Created At:** {item.get('created_at')}")
except requests.RequestException as exc:
    st.warning(f"Could not load incident history: {exc}")

st.subheader("Raw Incident Report JSON")
st.json(llm_response)
